version: "3.7"
services:
  dtj-server:
    container_name: dtj-server
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    links:
      - dtj-mongo
  dtj-client:
    container_name: dtj-client
    restart: always
    build: ./client
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/src/app
  dtj-mongo:
    container_name: dtj-mongo
    hostname: mongo
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
